# Generated by Django 4.0.3 on 2022-12-23 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phoneno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customertype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expencesdetails', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('helpername', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=250)),
                ('diesel', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('ed', models.IntegerField()),
                ('gl', models.IntegerField()),
                ('nonel', models.IntegerField(default=0)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.driver')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.helper')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=50)),
                ('itemdesc', models.CharField(max_length=150)),
                ('totalstock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tractorno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('1', 'Stock-in'), ('2', 'Stock-Out')], default=1, max_length=2)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Receiptinvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(default=0)),
                ('deposit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.invoice')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imsApp.site')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStockBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stockqty', models.FloatField(default=0)),
                ('stockistname', models.CharField(blank=True, max_length=2)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole25', models.FloatField(blank=True, default=0)),
                ('hole5', models.FloatField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=0)),
                ('deposit', models.FloatField(blank=True, default=0)),
                ('balance', models.FloatField(blank=True, default=0)),
                ('quantity', models.FloatField(blank=True, default=0)),
                ('total', models.FloatField(blank=True, default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.invoice')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.site')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='tractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsApp.tractor'),
        ),
    ]
