# Generated by Django 4.0.3 on 2022-12-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='thussi',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
