# Generated by Django 4.0.3 on 2022-12-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0002_invoice_item_thussi'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='df',
            field=models.IntegerField(default=0),
        ),
    ]
